[root@ansible-server playbook]# vi change_root_password.yml
---
- hosts : test
  vars :
    hostname_collector : "{{ ansible_hostname }}"
    hostname_split : "{{ hostname_collector.split('-')[1][0:3] }}"

  tasks:
    - debug:
        msg : "{{ hostname_split }}"

    - shell : 'echo "{{hostname_split}}1234" | passwd --stdin root'

[root@ansible-server playbook]# cat /etc/ansible/hosts
[test]
ansible-host1 ansible_host=192.168.182.151  ansible_connection=ssh
ansible-host6 ansible_host=192.168.182.156  ansible_connection=ssh
# 192.168.182.151 -> HOSTNAME = ansible-woobeom
# 192.168.182.156 -> HOSTNAME = ansible-host6

[root@ansible-server playbook]# ansible-playbook test.yml
PLAY [test] *********************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [ansible-host6]
ok: [ansible-host1]

TASK [debug] ********************************************************************************************
ok: [ansible-host1] => {
    "msg": "woo"
}
ok: [ansible-host6] => {
    "msg": "hos"
}

TASK [shell] ********************************************************************************************
changed: [ansible-host6]
changed: [ansible-host1]

PLAY RECAP **********************************************************************************************
ansible-host1              : ok=3    changed=1    unreachable=0    failed=0
ansible-host6              : ok=3    changed=1    unreachable=0    failed=0

