# https://docs.ansible.com/ansible/latest/modules/copy_module.html
# Synopsis: 
  - The copy module copies a file from the local or remote machine to a location on the remote machine.
  - Use the fetch module to copy files from remote locations to the local box.
  - If you need variable interpolation in copied files, use the template module. 
  Using a variable in the content field will result in unpredictable output.
  - For Windows targets, use the win_copy module instead.

# copy.yml
---
- name: TEST YAML Module
  hosts: test_user
  gather_facts: yes
  
  tasks: 
    - name: copy
      copy:
        src: /tmp/sources.list
        dest: /tmp/woobeom2
        mode: 0644
        
# src: /tmp/sources.list - 로컬서버의 sources.list가 리모트서버로 옮겨짐
# dest: /tmp/woobeom2 - woobeom2 파일에 sources.list의 내용을 입력함
# desg: /tmp/woobeom2/ - /tmp/woobeom2/ 디렉터리 아래에 sources.list 파일을 생성함, 만약 디렉터리가 없으면 생성함
        
    
